version: "3.6"
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "1234:80"
    volumes:
      - ./src:/var/www/html/
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
